# models/lead_data.py
from pydantic import BaseModel, Field
from typing import Optional

class LeadData(BaseModel):
    nome_cliente: Optional[str] = Field(None, description="Nome completo do cliente")
    pushname: Optional[str] = Field(None, description="PushName do WhatsApp")
    telefone: Optional[str] = Field(None, description="Número de telefone ou WhatsApp")
    cidade: Optional[str] = Field(None, description="Cidade do cliente")
    estado: Optional[str] = Field(None, description="Estado do cliente")
    email: Optional[str] = Field(None, description="Endereço de e-mail do cliente")
    tipo: Optional[str] = Field(None, description="Tipo do cliente (lojista, revendedor, sacoleiro, feirante)")
    data_aniversario: Optional[str] = Field(None, description="Data de aniversário do cliente (DD/MM/AAAA)")
    idioma: Optional[str] = Field(None, description="Idioma preferido do cliente")
    audio: Optional[bool] = Field(None, description="Preferência por respostas em áudio (true/false)")
    thread_id: Optional[str] = Field(None, description="Thread ID for conversation tracking")
    data_cadastro: Optional[str] = Field(None, description="Data de cadastro do lead")
    data_ultima_alteracao: Optional[str] = Field(None, description="Data da última alteração")
    ult_assunto: Optional[str] = Field(None, description="Último assunto tratado")
    id_google: Optional[str] = Field(None, description="ID do Google")
    followup: Optional[bool] = Field(None, description="Indicador de follow-up")
    followup_data: Optional[str] = Field(None, description="Data de follow-up")
    ult_contato: Optional[str] = Field(None, description="Data do último contato")
    cep: Optional[str] = Field(None, description="CEP do cliente")
    endereco: Optional[str] = Field(None, description="Endereço do cliente")
    adm: Optional[bool] = Field(None, description="Indicador de administrador")
    lead: Optional[int] = Field(None, description="ID do lead")
    instancia: Optional[str] = Field(None, description="Instância do lead")
    agente: Optional[bool] = Field(None, description="Indicador de agente")
    thread_ag: Optional[str] = Field(None, description="Thread ID do agente")
    conciencia: Optional[str] = Field(None, description="Nível de consciência do lead")
    ult_verifica_lead: Optional[str] = Field(None, description="Data da última verificação do lead")
    verificador: Optional[int] = Field(None, description="Verificador do lead")
    id_kommo: Optional[int] = Field(None, description="ID do Kommo")
    msg_erro: Optional[str] = Field(None, description="Mensagem de erro associada")
    sentimento: Optional[str] = Field(None, description="Sentimento da mensagem (positivo, negativo, neutro)")